spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/orchestrator_db
    username: orchestrator_user
    password: strong_password_here

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

anymodel:
  api:
    key: ${ANYMODEL_API_KEY:local_dev_key}
    base:
      url: ${ANYMODEL_BASE_URL:https://anymodel.org/v1}

app:
  output:
    directory: ./output

logging:
  level:
    ru.sergalas.orchestrator: DEBUG
    org.springframework.web: DEBUG