server {
    listen 80;
    server_name localhost;
    charset utf-8;

    root /usr/share/nginx/html;
    index index.html;

    # Allow CORS for all clients
    add_header Access-Control-Allow-Origin * always;
    add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
    add_header Access-Control-Allow-Headers "*" always;

    location / {
        default_type text/markdown;
        charset utf-8;
        try_files $uri $uri.md $uri.txt $uri.html $uri/ =404;
    }

    location ~* \.html$ {
        default_type text/html;
        charset utf-8;
    }

    location ~* \.(css|js|png|jpg|svg|ico)$ {
        try_files $uri =404;
    }
}
